# Generated by Django 2.2.3 on 2019-07-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nomor_telepon', models.CharField(max_length=50)),
                ('bidang', models.CharField(max_length=50)),
                ('jadwal_praktek', models.DateField(verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('kandungan', models.TextField()),
                ('khasiat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nomor_telepon', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
                ('keluhan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('total_harga', models.FloatField()),
                ('kumpulan_obat', models.TextField()),
            ],
        ),
    ]
