# Generated by Django 2.2.3 on 2019-07-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KebunBinatang', '0002_auto_20190722_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengunjung',
            name='hari_berkunjung',
            field=models.CharField(choices=[['Ming', 'Minggu'], ['Sen', 'Senin'], ['Sel', 'Selasa'], ['Rab', 'Rabu'], ['Kam', 'Kamis'], ['Jum', "Jum'at"], ['Sab', 'Sabtu']], default='Ming', max_length=2),
        ),
    ]
